### ISSUE TITLE
Incorrect license selected for ZipHandling module

### ISSUE THREAD

**Issue by lalitdeshpande** [webfryslan/ZipHandling#1]
Hi, I'm from Mendix Quality Compliance team.

ZipHandling module, which is a community supported module developed by Achmea, has been published on Mendix Marketplace under 'Mendix EULA' license (screenshot below), which is an incorrect license to choose. 

From Mendix perspective, it is a 3rd party product and must be under a non-Mendix license. E.g., Apache V2/MIT/BSD/GPL. 

Could you please change this license on Mendix Marketplace and also add the new license in the Github source code package?

Thanks,
Lalit 

![ZipHandling](https://user-images.githubusercontent.com/121277989/209277960-39cc88af-f6c1-43dd-bd1e-1ebee61a2823.jpg)

**Comment by webfryslan** [comment]
It is not possible to change the license in the app store, can someone from Mendix change the license?
