### ISSUE TITLE
Compile Error in Mendix 10

### ISSUE THREAD

**Issue by Aristocraties** [webfryslan/ZipHandling#3]
I get this error message when compiling related to zip handling

D:\Mendix\Blue Steel-Development\javasource\ziphandling\actions\ZipDocuments.java:88: error: cannot assign a value to final variable __ZipFile
	    __ZipFile = Core.instantiate(getContext(), "System.FileDocument");
	    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compile'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by webfryslan** [comment]
Version 4.0.3 is now available and compiling in Mendix 10
